//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskbarIconOverlay.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskbarIconOverlay.App.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add slot.
        /// </summary>
        internal static string AddSlot {
            get {
                return ResourceManager.GetString("AddSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow numbering beyond 10 (no Win+N).
        /// </summary>
        internal static string AllowBeyondTen {
            get {
                return ResourceManager.GetString("AllowBeyondTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline/background color.
        /// </summary>
        internal static string BackgroundColorLabel {
            get {
                return ResourceManager.GetString("BackgroundColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseIcon {
            get {
                return ResourceManager.GetString("BrowseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size (8-16).
        /// </summary>
        internal static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number color.
        /// </summary>
        internal static string NumberColorLabel {
            get {
                return ResourceManager.GetString("NumberColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of numbered windows.
        /// </summary>
        internal static string NumberedCountLabel {
            get {
                return ResourceManager.GetString("NumberedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number position.
        /// </summary>
        internal static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveSlot {
            get {
                return ResourceManager.GetString("RemoveSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show numbers on all taskbars.
        /// </summary>
        internal static string ShowOnAllTaskbars {
            get {
                return ResourceManager.GetString("ShowOnAllTaskbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin icon to window (not to position).
        /// </summary>
        internal static string StickyBinding {
            get {
                return ResourceManager.GetString("StickyBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string TabColors {
            get {
                return ResourceManager.GetString("TabColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        internal static string TabNumbering {
            get {
                return ResourceManager.GetString("TabNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows &amp; icons.
        /// </summary>
        internal static string TabSlots {
            get {
                return ResourceManager.GetString("TabSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string ToggleDisable {
            get {
                return ResourceManager.GetString("ToggleDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string ToggleEnable {
            get {
                return ResourceManager.GetString("ToggleEnable", resourceCulture);
            }
        }
    }
}
