//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskbarIconOverlay.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskbarIconOverlay.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add slot.
        /// </summary>
        internal static string AddSlot {
            get {
                return ResourceManager.GetString("AddSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow numbering beyond 10 (no Win+N).
        /// </summary>
        internal static string AllowBeyondTen {
            get {
                return ResourceManager.GetString("AllowBeyondTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline/background color.
        /// </summary>
        internal static string BackgroundColorLabel {
            get {
                return ResourceManager.GetString("BackgroundColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseIcon {
            get {
                return ResourceManager.GetString("BrowseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string LangRussian {
            get {
                return ResourceManager.GetString("LangRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        internal static string LangUkrainian {
            get {
                return ResourceManager.GetString("LangUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string MenuTheme {
            get {
                return ResourceManager.GetString("MenuTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string MenuThemeDark {
            get {
                return ResourceManager.GetString("MenuThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string MenuThemeLight {
            get {
                return ResourceManager.GetString("MenuThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number color.
        /// </summary>
        internal static string NumberColorLabel {
            get {
                return ResourceManager.GetString("NumberColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of numbered windows.
        /// </summary>
        internal static string NumberedCountLabel {
            get {
                return ResourceManager.GetString("NumberedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-left corner of the icon.
        /// </summary>
        internal static string PositionBottomLeft {
            get {
                return ResourceManager.GetString("PositionBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-right corner of the icon.
        /// </summary>
        internal static string PositionBottomRight {
            get {
                return ResourceManager.GetString("PositionBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number position.
        /// </summary>
        internal static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-left corner of the icon.
        /// </summary>
        internal static string PositionTopLeft {
            get {
                return ResourceManager.GetString("PositionTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-right corner of the icon.
        /// </summary>
        internal static string PositionTopRight {
            get {
                return ResourceManager.GetString("PositionTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveSlot {
            get {
                return ResourceManager.GetString("RemoveSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show numbers on all taskbars.
        /// </summary>
        internal static string ShowOnAllTaskbars {
            get {
                return ResourceManager.GetString("ShowOnAllTaskbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin icon to window (not to position).
        /// </summary>
        internal static string StickyBinding {
            get {
                return ResourceManager.GetString("StickyBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, an icon stays with the same window even if it moves to a different taskbar position. When disabled, icons follow position instead of the window..
        /// </summary>
        internal static string StickyBindingHint {
            get {
                return ResourceManager.GetString("StickyBindingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string TabColors {
            get {
                return ResourceManager.GetString("TabColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        internal static string TabNumbering {
            get {
                return ResourceManager.GetString("TabNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows &amp; icons.
        /// </summary>
        internal static string TabSlots {
            get {
                return ResourceManager.GetString("TabSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string ToggleDisable {
            get {
                return ResourceManager.GetString("ToggleDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string ToggleEnable {
            get {
                return ResourceManager.GetString("ToggleEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string ToggleWorking {
            get {
                return ResourceManager.GetString("ToggleWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string TrayShow {
            get {
                return ResourceManager.GetString("TrayShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskbarIconOverlay.
        /// </summary>
        internal static string TrayTooltip {
            get {
                return ResourceManager.GetString("TrayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskbarIconOverlay - taskbar icon overlays.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
